### ISSUE TITLE
NavBar Drop Shadow overlaps Scrollbar when Tweet with Replies is in view

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#87]
## Is something unstyled or looking weird?
- Expand a Tweet with many replies, creating a scrollbar. Twitter's Navbar Drop Shadow will overlay the Scrollbar, doesn't happen when a Tweet is not expanded.
- Class: Unknown
- Windows 10 x64, Chrome, 1920x1080

## URL of where this happens or steps to reproduce
- https://twitter.com/MrRoflWaffles/status/887371570024509440

## Screenshots
![image](https://user-images.githubusercontent.com/16727756/28341813-d86274da-6bda-11e7-84d5-95947954511d.png)

**Comment by EthanC** [comment]
Still seeing this issue after the latest update.

Though I've noticed something, not sure if this was present before...

Before the Tweet is fully-loaded, a secondary, smaller scrollbar is made, without this specific issue, but the Navbar overlaps it entirely
![image](https://user-images.githubusercontent.com/16727756/28344037-b2229adc-6be6-11e7-8198-95ae5fa9340c.png)

However, once fully-loaded, the issue is still present
![image](https://user-images.githubusercontent.com/16727756/28344049-c2430302-6be6-11e7-943f-d7813d2a5bd4.png)

**Comment by pugson** [comment]
Thanks for letting me know!

After debugging this issue, it turned out to be a problem with [gulp-cssnano](https://github.com/ben-eb/gulp-cssnano) trying to compress the file too much. It was overwriting `z-index` declarations. I [passed down an option](https://github.com/dubstrike/twitter-dark-mode/commit/c6e96acace8320370f443bb003d595facc36e1e5#diff-b9e12334e9eafd8341a6107dd98510c9R16) to prevent that behavior.
